// Code generated by ent, DO NOT EDIT.

package desktopsession

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldSessionID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldUserID, v))
}

// DeviceID applies equality check predicate on the "device_id" field. It's identical to DeviceIDEQ.
func DeviceID(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceName applies equality check predicate on the "device_name" field. It's identical to DeviceNameEQ.
func DeviceName(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldDeviceName, v))
}

// Target applies equality check predicate on the "target" field. It's identical to TargetEQ.
func Target(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldTarget, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldStatus, v))
}

// RuntimeTokenHash applies equality check predicate on the "runtime_token_hash" field. It's identical to RuntimeTokenHashEQ.
func RuntimeTokenHash(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldRuntimeTokenHash, v))
}

// ProfileKey applies equality check predicate on the "profile_key" field. It's identical to ProfileKeyEQ.
func ProfileKey(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldProfileKey, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldExpiresAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldLastSeenAt, v))
}

// RevokedAt applies equality check predicate on the "revoked_at" field. It's identical to RevokedAtEQ.
func RevokedAt(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldRevokedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldUpdatedAt, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldSessionID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldUserID, v))
}

// DeviceIDEQ applies the EQ predicate on the "device_id" field.
func DeviceIDEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldDeviceID, v))
}

// DeviceIDNEQ applies the NEQ predicate on the "device_id" field.
func DeviceIDNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldDeviceID, v))
}

// DeviceIDIn applies the In predicate on the "device_id" field.
func DeviceIDIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldDeviceID, vs...))
}

// DeviceIDNotIn applies the NotIn predicate on the "device_id" field.
func DeviceIDNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldDeviceID, vs...))
}

// DeviceIDGT applies the GT predicate on the "device_id" field.
func DeviceIDGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldDeviceID, v))
}

// DeviceIDGTE applies the GTE predicate on the "device_id" field.
func DeviceIDGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldDeviceID, v))
}

// DeviceIDLT applies the LT predicate on the "device_id" field.
func DeviceIDLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldDeviceID, v))
}

// DeviceIDLTE applies the LTE predicate on the "device_id" field.
func DeviceIDLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldDeviceID, v))
}

// DeviceIDContains applies the Contains predicate on the "device_id" field.
func DeviceIDContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldDeviceID, v))
}

// DeviceIDHasPrefix applies the HasPrefix predicate on the "device_id" field.
func DeviceIDHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldDeviceID, v))
}

// DeviceIDHasSuffix applies the HasSuffix predicate on the "device_id" field.
func DeviceIDHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldDeviceID, v))
}

// DeviceIDEqualFold applies the EqualFold predicate on the "device_id" field.
func DeviceIDEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldDeviceID, v))
}

// DeviceIDContainsFold applies the ContainsFold predicate on the "device_id" field.
func DeviceIDContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldDeviceID, v))
}

// DeviceNameEQ applies the EQ predicate on the "device_name" field.
func DeviceNameEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldDeviceName, v))
}

// DeviceNameNEQ applies the NEQ predicate on the "device_name" field.
func DeviceNameNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldDeviceName, v))
}

// DeviceNameIn applies the In predicate on the "device_name" field.
func DeviceNameIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldDeviceName, vs...))
}

// DeviceNameNotIn applies the NotIn predicate on the "device_name" field.
func DeviceNameNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldDeviceName, vs...))
}

// DeviceNameGT applies the GT predicate on the "device_name" field.
func DeviceNameGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldDeviceName, v))
}

// DeviceNameGTE applies the GTE predicate on the "device_name" field.
func DeviceNameGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldDeviceName, v))
}

// DeviceNameLT applies the LT predicate on the "device_name" field.
func DeviceNameLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldDeviceName, v))
}

// DeviceNameLTE applies the LTE predicate on the "device_name" field.
func DeviceNameLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldDeviceName, v))
}

// DeviceNameContains applies the Contains predicate on the "device_name" field.
func DeviceNameContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldDeviceName, v))
}

// DeviceNameHasPrefix applies the HasPrefix predicate on the "device_name" field.
func DeviceNameHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldDeviceName, v))
}

// DeviceNameHasSuffix applies the HasSuffix predicate on the "device_name" field.
func DeviceNameHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldDeviceName, v))
}

// DeviceNameEqualFold applies the EqualFold predicate on the "device_name" field.
func DeviceNameEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldDeviceName, v))
}

// DeviceNameContainsFold applies the ContainsFold predicate on the "device_name" field.
func DeviceNameContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldDeviceName, v))
}

// TargetEQ applies the EQ predicate on the "target" field.
func TargetEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldTarget, v))
}

// TargetNEQ applies the NEQ predicate on the "target" field.
func TargetNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldTarget, v))
}

// TargetIn applies the In predicate on the "target" field.
func TargetIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldTarget, vs...))
}

// TargetNotIn applies the NotIn predicate on the "target" field.
func TargetNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldTarget, vs...))
}

// TargetGT applies the GT predicate on the "target" field.
func TargetGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldTarget, v))
}

// TargetGTE applies the GTE predicate on the "target" field.
func TargetGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldTarget, v))
}

// TargetLT applies the LT predicate on the "target" field.
func TargetLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldTarget, v))
}

// TargetLTE applies the LTE predicate on the "target" field.
func TargetLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldTarget, v))
}

// TargetContains applies the Contains predicate on the "target" field.
func TargetContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldTarget, v))
}

// TargetHasPrefix applies the HasPrefix predicate on the "target" field.
func TargetHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldTarget, v))
}

// TargetHasSuffix applies the HasSuffix predicate on the "target" field.
func TargetHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldTarget, v))
}

// TargetEqualFold applies the EqualFold predicate on the "target" field.
func TargetEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldTarget, v))
}

// TargetContainsFold applies the ContainsFold predicate on the "target" field.
func TargetContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldTarget, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldStatus, v))
}

// RuntimeTokenHashEQ applies the EQ predicate on the "runtime_token_hash" field.
func RuntimeTokenHashEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashNEQ applies the NEQ predicate on the "runtime_token_hash" field.
func RuntimeTokenHashNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashIn applies the In predicate on the "runtime_token_hash" field.
func RuntimeTokenHashIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldRuntimeTokenHash, vs...))
}

// RuntimeTokenHashNotIn applies the NotIn predicate on the "runtime_token_hash" field.
func RuntimeTokenHashNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldRuntimeTokenHash, vs...))
}

// RuntimeTokenHashGT applies the GT predicate on the "runtime_token_hash" field.
func RuntimeTokenHashGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashGTE applies the GTE predicate on the "runtime_token_hash" field.
func RuntimeTokenHashGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashLT applies the LT predicate on the "runtime_token_hash" field.
func RuntimeTokenHashLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashLTE applies the LTE predicate on the "runtime_token_hash" field.
func RuntimeTokenHashLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashContains applies the Contains predicate on the "runtime_token_hash" field.
func RuntimeTokenHashContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashHasPrefix applies the HasPrefix predicate on the "runtime_token_hash" field.
func RuntimeTokenHashHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashHasSuffix applies the HasSuffix predicate on the "runtime_token_hash" field.
func RuntimeTokenHashHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashEqualFold applies the EqualFold predicate on the "runtime_token_hash" field.
func RuntimeTokenHashEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldRuntimeTokenHash, v))
}

// RuntimeTokenHashContainsFold applies the ContainsFold predicate on the "runtime_token_hash" field.
func RuntimeTokenHashContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldRuntimeTokenHash, v))
}

// ProfileKeyEQ applies the EQ predicate on the "profile_key" field.
func ProfileKeyEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldProfileKey, v))
}

// ProfileKeyNEQ applies the NEQ predicate on the "profile_key" field.
func ProfileKeyNEQ(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldProfileKey, v))
}

// ProfileKeyIn applies the In predicate on the "profile_key" field.
func ProfileKeyIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldProfileKey, vs...))
}

// ProfileKeyNotIn applies the NotIn predicate on the "profile_key" field.
func ProfileKeyNotIn(vs ...string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldProfileKey, vs...))
}

// ProfileKeyGT applies the GT predicate on the "profile_key" field.
func ProfileKeyGT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldProfileKey, v))
}

// ProfileKeyGTE applies the GTE predicate on the "profile_key" field.
func ProfileKeyGTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldProfileKey, v))
}

// ProfileKeyLT applies the LT predicate on the "profile_key" field.
func ProfileKeyLT(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldProfileKey, v))
}

// ProfileKeyLTE applies the LTE predicate on the "profile_key" field.
func ProfileKeyLTE(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldProfileKey, v))
}

// ProfileKeyContains applies the Contains predicate on the "profile_key" field.
func ProfileKeyContains(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContains(FieldProfileKey, v))
}

// ProfileKeyHasPrefix applies the HasPrefix predicate on the "profile_key" field.
func ProfileKeyHasPrefix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasPrefix(FieldProfileKey, v))
}

// ProfileKeyHasSuffix applies the HasSuffix predicate on the "profile_key" field.
func ProfileKeyHasSuffix(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldHasSuffix(FieldProfileKey, v))
}

// ProfileKeyEqualFold applies the EqualFold predicate on the "profile_key" field.
func ProfileKeyEqualFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEqualFold(FieldProfileKey, v))
}

// ProfileKeyContainsFold applies the ContainsFold predicate on the "profile_key" field.
func ProfileKeyContainsFold(v string) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldContainsFold(FieldProfileKey, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldExpiresAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldLastSeenAt, v))
}

// RevokedAtEQ applies the EQ predicate on the "revoked_at" field.
func RevokedAtEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldEQ(FieldRevokedAt, v))
}

// RevokedAtNEQ applies the NEQ predicate on the "revoked_at" field.
func RevokedAtNEQ(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNEQ(FieldRevokedAt, v))
}

// RevokedAtIn applies the In predicate on the "revoked_at" field.
func RevokedAtIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIn(FieldRevokedAt, vs...))
}

// RevokedAtNotIn applies the NotIn predicate on the "revoked_at" field.
func RevokedAtNotIn(vs ...time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotIn(FieldRevokedAt, vs...))
}

// RevokedAtGT applies the GT predicate on the "revoked_at" field.
func RevokedAtGT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGT(FieldRevokedAt, v))
}

// RevokedAtGTE applies the GTE predicate on the "revoked_at" field.
func RevokedAtGTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldGTE(FieldRevokedAt, v))
}

// RevokedAtLT applies the LT predicate on the "revoked_at" field.
func RevokedAtLT(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLT(FieldRevokedAt, v))
}

// RevokedAtLTE applies the LTE predicate on the "revoked_at" field.
func RevokedAtLTE(v time.Time) predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldLTE(FieldRevokedAt, v))
}

// RevokedAtIsNil applies the IsNil predicate on the "revoked_at" field.
func RevokedAtIsNil() predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldIsNull(FieldRevokedAt))
}

// RevokedAtNotNil applies the NotNil predicate on the "revoked_at" field.
func RevokedAtNotNil() predicate.DesktopSession {
	return predicate.DesktopSession(sql.FieldNotNull(FieldRevokedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DesktopSession) predicate.DesktopSession {
	return predicate.DesktopSession(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DesktopSession) predicate.DesktopSession {
	return predicate.DesktopSession(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DesktopSession) predicate.DesktopSession {
	return predicate.DesktopSession(sql.NotPredicates(p))
}
