// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopsession"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// DesktopSessionUpdate is the builder for updating DesktopSession entities.
type DesktopSessionUpdate struct {
	config
	hooks    []Hook
	mutation *DesktopSessionMutation
}

// Where appends a list predicates to the DesktopSessionUpdate builder.
func (_u *DesktopSessionUpdate) Where(ps ...predicate.DesktopSession) *DesktopSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopSessionUpdate) SetUpdatedAt(v time.Time) *DesktopSessionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *DesktopSessionUpdate) SetSessionID(v string) *DesktopSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableSessionID(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopSessionUpdate) SetUserID(v int64) *DesktopSessionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableUserID(v *int64) *DesktopSessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DesktopSessionUpdate) AddUserID(v int64) *DesktopSessionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DesktopSessionUpdate) SetGroupID(v int64) *DesktopSessionUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableGroupID(v *int64) *DesktopSessionUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *DesktopSessionUpdate) AddGroupID(v int64) *DesktopSessionUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopSessionUpdate) SetDeviceID(v string) *DesktopSessionUpdate {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableDeviceID(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DesktopSessionUpdate) SetDeviceName(v string) *DesktopSessionUpdate {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableDeviceName(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *DesktopSessionUpdate) SetTarget(v string) *DesktopSessionUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableTarget(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopSessionUpdate) SetStatus(v string) *DesktopSessionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableStatus(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRuntimeTokenHash sets the "runtime_token_hash" field.
func (_u *DesktopSessionUpdate) SetRuntimeTokenHash(v string) *DesktopSessionUpdate {
	_u.mutation.SetRuntimeTokenHash(v)
	return _u
}

// SetNillableRuntimeTokenHash sets the "runtime_token_hash" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableRuntimeTokenHash(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetRuntimeTokenHash(*v)
	}
	return _u
}

// SetProfileKey sets the "profile_key" field.
func (_u *DesktopSessionUpdate) SetProfileKey(v string) *DesktopSessionUpdate {
	_u.mutation.SetProfileKey(v)
	return _u
}

// SetNillableProfileKey sets the "profile_key" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableProfileKey(v *string) *DesktopSessionUpdate {
	if v != nil {
		_u.SetProfileKey(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopSessionUpdate) SetExpiresAt(v time.Time) *DesktopSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableExpiresAt(v *time.Time) *DesktopSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DesktopSessionUpdate) SetLastSeenAt(v time.Time) *DesktopSessionUpdate {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableLastSeenAt(v *time.Time) *DesktopSessionUpdate {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopSessionUpdate) SetRevokedAt(v time.Time) *DesktopSessionUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopSessionUpdate) SetNillableRevokedAt(v *time.Time) *DesktopSessionUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopSessionUpdate) ClearRevokedAt() *DesktopSessionUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the DesktopSessionMutation object of the builder.
func (_u *DesktopSessionUpdate) Mutation() *DesktopSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DesktopSessionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DesktopSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopSessionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DesktopSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(desktopsession.Table, desktopsession.Columns, sqlgraph.NewFieldSpec(desktopsession.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(desktopsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(desktopsession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(desktopsession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(desktopsession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(desktopsession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(desktopsession.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(desktopsession.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(desktopsession.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuntimeTokenHash(); ok {
		_spec.SetField(desktopsession.FieldRuntimeTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileKey(); ok {
		_spec.SetField(desktopsession.FieldProfileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(desktopsession.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopsession.FieldRevokedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DesktopSessionUpdateOne is the builder for updating a single DesktopSession entity.
type DesktopSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DesktopSessionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DesktopSessionUpdateOne) SetUpdatedAt(v time.Time) *DesktopSessionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *DesktopSessionUpdateOne) SetSessionID(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableSessionID(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *DesktopSessionUpdateOne) SetUserID(v int64) *DesktopSessionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableUserID(v *int64) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *DesktopSessionUpdateOne) AddUserID(v int64) *DesktopSessionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *DesktopSessionUpdateOne) SetGroupID(v int64) *DesktopSessionUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableGroupID(v *int64) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *DesktopSessionUpdateOne) AddGroupID(v int64) *DesktopSessionUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetDeviceID sets the "device_id" field.
func (_u *DesktopSessionUpdateOne) SetDeviceID(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetDeviceID(v)
	return _u
}

// SetNillableDeviceID sets the "device_id" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableDeviceID(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetDeviceID(*v)
	}
	return _u
}

// SetDeviceName sets the "device_name" field.
func (_u *DesktopSessionUpdateOne) SetDeviceName(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetDeviceName(v)
	return _u
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableDeviceName(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetDeviceName(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *DesktopSessionUpdateOne) SetTarget(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableTarget(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DesktopSessionUpdateOne) SetStatus(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableStatus(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRuntimeTokenHash sets the "runtime_token_hash" field.
func (_u *DesktopSessionUpdateOne) SetRuntimeTokenHash(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetRuntimeTokenHash(v)
	return _u
}

// SetNillableRuntimeTokenHash sets the "runtime_token_hash" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableRuntimeTokenHash(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetRuntimeTokenHash(*v)
	}
	return _u
}

// SetProfileKey sets the "profile_key" field.
func (_u *DesktopSessionUpdateOne) SetProfileKey(v string) *DesktopSessionUpdateOne {
	_u.mutation.SetProfileKey(v)
	return _u
}

// SetNillableProfileKey sets the "profile_key" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableProfileKey(v *string) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetProfileKey(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *DesktopSessionUpdateOne) SetExpiresAt(v time.Time) *DesktopSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_u *DesktopSessionUpdateOne) SetLastSeenAt(v time.Time) *DesktopSessionUpdateOne {
	_u.mutation.SetLastSeenAt(v)
	return _u
}

// SetNillableLastSeenAt sets the "last_seen_at" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableLastSeenAt(v *time.Time) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetLastSeenAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *DesktopSessionUpdateOne) SetRevokedAt(v time.Time) *DesktopSessionUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *DesktopSessionUpdateOne) SetNillableRevokedAt(v *time.Time) *DesktopSessionUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *DesktopSessionUpdateOne) ClearRevokedAt() *DesktopSessionUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// Mutation returns the DesktopSessionMutation object of the builder.
func (_u *DesktopSessionUpdateOne) Mutation() *DesktopSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the DesktopSessionUpdate builder.
func (_u *DesktopSessionUpdateOne) Where(ps ...predicate.DesktopSession) *DesktopSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DesktopSessionUpdateOne) Select(field string, fields ...string) *DesktopSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DesktopSession entity.
func (_u *DesktopSessionUpdateOne) Save(ctx context.Context) (*DesktopSession, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DesktopSessionUpdateOne) SaveX(ctx context.Context) *DesktopSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DesktopSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DesktopSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DesktopSessionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := desktopsession.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DesktopSessionUpdateOne) sqlSave(ctx context.Context) (_node *DesktopSession, err error) {
	_spec := sqlgraph.NewUpdateSpec(desktopsession.Table, desktopsession.Columns, sqlgraph.NewFieldSpec(desktopsession.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DesktopSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, desktopsession.FieldID)
		for _, f := range fields {
			if !desktopsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != desktopsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopsession.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(desktopsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(desktopsession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(desktopsession.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(desktopsession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(desktopsession.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeviceID(); ok {
		_spec.SetField(desktopsession.FieldDeviceID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceName(); ok {
		_spec.SetField(desktopsession.FieldDeviceName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(desktopsession.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(desktopsession.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuntimeTokenHash(); ok {
		_spec.SetField(desktopsession.FieldRuntimeTokenHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProfileKey(); ok {
		_spec.SetField(desktopsession.FieldProfileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeenAt(); ok {
		_spec.SetField(desktopsession.FieldLastSeenAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(desktopsession.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(desktopsession.FieldRevokedAt, field.TypeTime)
	}
	_node = &DesktopSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{desktopsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
