// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/desktopsession"
)

// DesktopSessionCreate is the builder for creating a DesktopSession entity.
type DesktopSessionCreate struct {
	config
	mutation *DesktopSessionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DesktopSessionCreate) SetCreatedAt(v time.Time) *DesktopSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DesktopSessionCreate) SetNillableCreatedAt(v *time.Time) *DesktopSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DesktopSessionCreate) SetUpdatedAt(v time.Time) *DesktopSessionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DesktopSessionCreate) SetNillableUpdatedAt(v *time.Time) *DesktopSessionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *DesktopSessionCreate) SetSessionID(v string) *DesktopSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DesktopSessionCreate) SetUserID(v int64) *DesktopSessionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *DesktopSessionCreate) SetGroupID(v int64) *DesktopSessionCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetDeviceID sets the "device_id" field.
func (_c *DesktopSessionCreate) SetDeviceID(v string) *DesktopSessionCreate {
	_c.mutation.SetDeviceID(v)
	return _c
}

// SetDeviceName sets the "device_name" field.
func (_c *DesktopSessionCreate) SetDeviceName(v string) *DesktopSessionCreate {
	_c.mutation.SetDeviceName(v)
	return _c
}

// SetNillableDeviceName sets the "device_name" field if the given value is not nil.
func (_c *DesktopSessionCreate) SetNillableDeviceName(v *string) *DesktopSessionCreate {
	if v != nil {
		_c.SetDeviceName(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *DesktopSessionCreate) SetTarget(v string) *DesktopSessionCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *DesktopSessionCreate) SetStatus(v string) *DesktopSessionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DesktopSessionCreate) SetNillableStatus(v *string) *DesktopSessionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRuntimeTokenHash sets the "runtime_token_hash" field.
func (_c *DesktopSessionCreate) SetRuntimeTokenHash(v string) *DesktopSessionCreate {
	_c.mutation.SetRuntimeTokenHash(v)
	return _c
}

// SetProfileKey sets the "profile_key" field.
func (_c *DesktopSessionCreate) SetProfileKey(v string) *DesktopSessionCreate {
	_c.mutation.SetProfileKey(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *DesktopSessionCreate) SetExpiresAt(v time.Time) *DesktopSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetLastSeenAt sets the "last_seen_at" field.
func (_c *DesktopSessionCreate) SetLastSeenAt(v time.Time) *DesktopSessionCreate {
	_c.mutation.SetLastSeenAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *DesktopSessionCreate) SetRevokedAt(v time.Time) *DesktopSessionCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *DesktopSessionCreate) SetNillableRevokedAt(v *time.Time) *DesktopSessionCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// Mutation returns the DesktopSessionMutation object of the builder.
func (_c *DesktopSessionCreate) Mutation() *DesktopSessionMutation {
	return _c.mutation
}

// Save creates the DesktopSession in the database.
func (_c *DesktopSessionCreate) Save(ctx context.Context) (*DesktopSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DesktopSessionCreate) SaveX(ctx context.Context) *DesktopSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DesktopSessionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := desktopsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := desktopsession.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		v := desktopsession.DefaultDeviceName
		_c.mutation.SetDeviceName(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := desktopsession.DefaultStatus
		_c.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DesktopSessionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DesktopSession.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DesktopSession.updated_at"`)}
	}
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "DesktopSession.session_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DesktopSession.user_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "DesktopSession.group_id"`)}
	}
	if _, ok := _c.mutation.DeviceID(); !ok {
		return &ValidationError{Name: "device_id", err: errors.New(`ent: missing required field "DesktopSession.device_id"`)}
	}
	if _, ok := _c.mutation.DeviceName(); !ok {
		return &ValidationError{Name: "device_name", err: errors.New(`ent: missing required field "DesktopSession.device_name"`)}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "DesktopSession.target"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "DesktopSession.status"`)}
	}
	if _, ok := _c.mutation.RuntimeTokenHash(); !ok {
		return &ValidationError{Name: "runtime_token_hash", err: errors.New(`ent: missing required field "DesktopSession.runtime_token_hash"`)}
	}
	if _, ok := _c.mutation.ProfileKey(); !ok {
		return &ValidationError{Name: "profile_key", err: errors.New(`ent: missing required field "DesktopSession.profile_key"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "DesktopSession.expires_at"`)}
	}
	if _, ok := _c.mutation.LastSeenAt(); !ok {
		return &ValidationError{Name: "last_seen_at", err: errors.New(`ent: missing required field "DesktopSession.last_seen_at"`)}
	}
	return nil
}

func (_c *DesktopSessionCreate) sqlSave(ctx context.Context) (*DesktopSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DesktopSessionCreate) createSpec() (*DesktopSession, *sqlgraph.CreateSpec) {
	var (
		_node = &DesktopSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(desktopsession.Table, sqlgraph.NewFieldSpec(desktopsession.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(desktopsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(desktopsession.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(desktopsession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(desktopsession.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(desktopsession.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.DeviceID(); ok {
		_spec.SetField(desktopsession.FieldDeviceID, field.TypeString, value)
		_node.DeviceID = value
	}
	if value, ok := _c.mutation.DeviceName(); ok {
		_spec.SetField(desktopsession.FieldDeviceName, field.TypeString, value)
		_node.DeviceName = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(desktopsession.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(desktopsession.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RuntimeTokenHash(); ok {
		_spec.SetField(desktopsession.FieldRuntimeTokenHash, field.TypeString, value)
		_node.RuntimeTokenHash = value
	}
	if value, ok := _c.mutation.ProfileKey(); ok {
		_spec.SetField(desktopsession.FieldProfileKey, field.TypeString, value)
		_node.ProfileKey = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(desktopsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.LastSeenAt(); ok {
		_spec.SetField(desktopsession.FieldLastSeenAt, field.TypeTime, value)
		_node.LastSeenAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(desktopsession.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopSession.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopSessionCreate) OnConflict(opts ...sql.ConflictOption) *DesktopSessionUpsertOne {
	_c.conflict = opts
	return &DesktopSessionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopSessionCreate) OnConflictColumns(columns ...string) *DesktopSessionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopSessionUpsertOne{
		create: _c,
	}
}

type (
	// DesktopSessionUpsertOne is the builder for "upsert"-ing
	//  one DesktopSession node.
	DesktopSessionUpsertOne struct {
		create *DesktopSessionCreate
	}

	// DesktopSessionUpsert is the "OnConflict" setter.
	DesktopSessionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopSessionUpsert) SetUpdatedAt(v time.Time) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateUpdatedAt() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldUpdatedAt)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *DesktopSessionUpsert) SetSessionID(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateSessionID() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldSessionID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DesktopSessionUpsert) SetUserID(v int64) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateUserID() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *DesktopSessionUpsert) AddUserID(v int64) *DesktopSessionUpsert {
	u.Add(desktopsession.FieldUserID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *DesktopSessionUpsert) SetGroupID(v int64) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateGroupID() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *DesktopSessionUpsert) AddGroupID(v int64) *DesktopSessionUpsert {
	u.Add(desktopsession.FieldGroupID, v)
	return u
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopSessionUpsert) SetDeviceID(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldDeviceID, v)
	return u
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateDeviceID() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldDeviceID)
	return u
}

// SetDeviceName sets the "device_name" field.
func (u *DesktopSessionUpsert) SetDeviceName(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldDeviceName, v)
	return u
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateDeviceName() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldDeviceName)
	return u
}

// SetTarget sets the "target" field.
func (u *DesktopSessionUpsert) SetTarget(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldTarget, v)
	return u
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateTarget() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldTarget)
	return u
}

// SetStatus sets the "status" field.
func (u *DesktopSessionUpsert) SetStatus(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateStatus() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldStatus)
	return u
}

// SetRuntimeTokenHash sets the "runtime_token_hash" field.
func (u *DesktopSessionUpsert) SetRuntimeTokenHash(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldRuntimeTokenHash, v)
	return u
}

// UpdateRuntimeTokenHash sets the "runtime_token_hash" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateRuntimeTokenHash() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldRuntimeTokenHash)
	return u
}

// SetProfileKey sets the "profile_key" field.
func (u *DesktopSessionUpsert) SetProfileKey(v string) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldProfileKey, v)
	return u
}

// UpdateProfileKey sets the "profile_key" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateProfileKey() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldProfileKey)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopSessionUpsert) SetExpiresAt(v time.Time) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateExpiresAt() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldExpiresAt)
	return u
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *DesktopSessionUpsert) SetLastSeenAt(v time.Time) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldLastSeenAt, v)
	return u
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateLastSeenAt() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldLastSeenAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopSessionUpsert) SetRevokedAt(v time.Time) *DesktopSessionUpsert {
	u.Set(desktopsession.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopSessionUpsert) UpdateRevokedAt() *DesktopSessionUpsert {
	u.SetExcluded(desktopsession.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopSessionUpsert) ClearRevokedAt() *DesktopSessionUpsert {
	u.SetNull(desktopsession.FieldRevokedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DesktopSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopSessionUpsertOne) UpdateNewValues() *DesktopSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(desktopsession.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopSession.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DesktopSessionUpsertOne) Ignore() *DesktopSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopSessionUpsertOne) DoNothing() *DesktopSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopSessionCreate.OnConflict
// documentation for more info.
func (u *DesktopSessionUpsertOne) Update(set func(*DesktopSessionUpsert)) *DesktopSessionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopSessionUpsertOne) SetUpdatedAt(v time.Time) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateUpdatedAt() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSessionID sets the "session_id" field.
func (u *DesktopSessionUpsertOne) SetSessionID(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateSessionID() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateSessionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *DesktopSessionUpsertOne) SetUserID(v int64) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *DesktopSessionUpsertOne) AddUserID(v int64) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateUserID() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DesktopSessionUpsertOne) SetGroupID(v int64) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *DesktopSessionUpsertOne) AddGroupID(v int64) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateGroupID() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopSessionUpsertOne) SetDeviceID(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateDeviceID() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *DesktopSessionUpsertOne) SetDeviceName(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateDeviceName() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateDeviceName()
	})
}

// SetTarget sets the "target" field.
func (u *DesktopSessionUpsertOne) SetTarget(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateTarget() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateTarget()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopSessionUpsertOne) SetStatus(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateStatus() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetRuntimeTokenHash sets the "runtime_token_hash" field.
func (u *DesktopSessionUpsertOne) SetRuntimeTokenHash(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetRuntimeTokenHash(v)
	})
}

// UpdateRuntimeTokenHash sets the "runtime_token_hash" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateRuntimeTokenHash() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateRuntimeTokenHash()
	})
}

// SetProfileKey sets the "profile_key" field.
func (u *DesktopSessionUpsertOne) SetProfileKey(v string) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetProfileKey(v)
	})
}

// UpdateProfileKey sets the "profile_key" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateProfileKey() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateProfileKey()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopSessionUpsertOne) SetExpiresAt(v time.Time) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateExpiresAt() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *DesktopSessionUpsertOne) SetLastSeenAt(v time.Time) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateLastSeenAt() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopSessionUpsertOne) SetRevokedAt(v time.Time) *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertOne) UpdateRevokedAt() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopSessionUpsertOne) ClearRevokedAt() *DesktopSessionUpsertOne {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *DesktopSessionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopSessionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopSessionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DesktopSessionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DesktopSessionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DesktopSessionCreateBulk is the builder for creating many DesktopSession entities in bulk.
type DesktopSessionCreateBulk struct {
	config
	err      error
	builders []*DesktopSessionCreate
	conflict []sql.ConflictOption
}

// Save creates the DesktopSession entities in the database.
func (_c *DesktopSessionCreateBulk) Save(ctx context.Context) ([]*DesktopSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DesktopSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DesktopSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DesktopSessionCreateBulk) SaveX(ctx context.Context) []*DesktopSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DesktopSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DesktopSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DesktopSession.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DesktopSessionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DesktopSessionCreateBulk) OnConflict(opts ...sql.ConflictOption) *DesktopSessionUpsertBulk {
	_c.conflict = opts
	return &DesktopSessionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DesktopSession.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DesktopSessionCreateBulk) OnConflictColumns(columns ...string) *DesktopSessionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DesktopSessionUpsertBulk{
		create: _c,
	}
}

// DesktopSessionUpsertBulk is the builder for "upsert"-ing
// a bulk of DesktopSession nodes.
type DesktopSessionUpsertBulk struct {
	create *DesktopSessionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DesktopSession.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DesktopSessionUpsertBulk) UpdateNewValues() *DesktopSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(desktopsession.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DesktopSession.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DesktopSessionUpsertBulk) Ignore() *DesktopSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DesktopSessionUpsertBulk) DoNothing() *DesktopSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DesktopSessionCreateBulk.OnConflict
// documentation for more info.
func (u *DesktopSessionUpsertBulk) Update(set func(*DesktopSessionUpsert)) *DesktopSessionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DesktopSessionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DesktopSessionUpsertBulk) SetUpdatedAt(v time.Time) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateUpdatedAt() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetSessionID sets the "session_id" field.
func (u *DesktopSessionUpsertBulk) SetSessionID(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateSessionID() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateSessionID()
	})
}

// SetUserID sets the "user_id" field.
func (u *DesktopSessionUpsertBulk) SetUserID(v int64) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *DesktopSessionUpsertBulk) AddUserID(v int64) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateUserID() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateUserID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *DesktopSessionUpsertBulk) SetGroupID(v int64) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *DesktopSessionUpsertBulk) AddGroupID(v int64) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateGroupID() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateGroupID()
	})
}

// SetDeviceID sets the "device_id" field.
func (u *DesktopSessionUpsertBulk) SetDeviceID(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetDeviceID(v)
	})
}

// UpdateDeviceID sets the "device_id" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateDeviceID() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateDeviceID()
	})
}

// SetDeviceName sets the "device_name" field.
func (u *DesktopSessionUpsertBulk) SetDeviceName(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetDeviceName(v)
	})
}

// UpdateDeviceName sets the "device_name" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateDeviceName() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateDeviceName()
	})
}

// SetTarget sets the "target" field.
func (u *DesktopSessionUpsertBulk) SetTarget(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetTarget(v)
	})
}

// UpdateTarget sets the "target" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateTarget() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateTarget()
	})
}

// SetStatus sets the "status" field.
func (u *DesktopSessionUpsertBulk) SetStatus(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateStatus() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateStatus()
	})
}

// SetRuntimeTokenHash sets the "runtime_token_hash" field.
func (u *DesktopSessionUpsertBulk) SetRuntimeTokenHash(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetRuntimeTokenHash(v)
	})
}

// UpdateRuntimeTokenHash sets the "runtime_token_hash" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateRuntimeTokenHash() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateRuntimeTokenHash()
	})
}

// SetProfileKey sets the "profile_key" field.
func (u *DesktopSessionUpsertBulk) SetProfileKey(v string) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetProfileKey(v)
	})
}

// UpdateProfileKey sets the "profile_key" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateProfileKey() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateProfileKey()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *DesktopSessionUpsertBulk) SetExpiresAt(v time.Time) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateExpiresAt() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetLastSeenAt sets the "last_seen_at" field.
func (u *DesktopSessionUpsertBulk) SetLastSeenAt(v time.Time) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetLastSeenAt(v)
	})
}

// UpdateLastSeenAt sets the "last_seen_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateLastSeenAt() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateLastSeenAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *DesktopSessionUpsertBulk) SetRevokedAt(v time.Time) *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *DesktopSessionUpsertBulk) UpdateRevokedAt() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *DesktopSessionUpsertBulk) ClearRevokedAt() *DesktopSessionUpsertBulk {
	return u.Update(func(s *DesktopSessionUpsert) {
		s.ClearRevokedAt()
	})
}

// Exec executes the query.
func (u *DesktopSessionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DesktopSessionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DesktopSessionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DesktopSessionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
